FROM node:alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

FROM node:alpine

WORKDIR /app

COPY --from=build /app /app

EXPOSE $PORT

CMD npx prisma migrate dev && npm run start:dev
